### PR TITLE
implements /error mapping to serve styled unhandled errors

### PR DESCRIPTION
**Pull request by cwolfes**
## Delivers a generic error page when error is not handled with in the application.

Tested with a direct request on <IP:PORT>/api/v1/authc
Selection_417

_The implementation is inspired by:_
https://www.baeldung.com/spring-boot-custom-error-page

### CODE REVIEW

**Comment by cwolfes** [comment]
resolves #85

**Comment by ppxl** [comment]
Just a heads up, but if the issue is a bug then the branch `feature/...` is mislabeled :smile:

**Comment by cwolfes** [comment]
> Just a heads up, but if the issue is a bug then the branch `feature/...` is mislabeled

It is definitely a feature! I relabeled the issue.

**Comment by ppxl** [comment]
lgtm

**Pull request merged**
